name: Check Spelling

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  spelling:
    name: Check Spelling
    permissions:
      contents: read
      pull-requests: write
      actions: read
    outputs:
      followup: ${{ steps.spelling.outputs.followup }}
    runs-on: ubuntu-latest
    concurrency:
      group: spelling-${{ github.event.pull_request.number || github.ref }}
      # note: If you use only_check_changed_files, you do not want cancel-in-progress
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v4
    - name: check-spelling
      id: spelling
      uses: check-spelling/check-spelling@main
      with:
        suppress_push_for_open_pull_request: ${{ github.actor != 'dependabot[bot]' && 1 }}
        checkout: true
        check_file_names: 1
        post_comment: 0
        use_magic_file: 1
        report-timing: 1
        warnings: bad-regex,binary-file,deprecated-feature,large-file,limited-references,no-newline-at-eof,noisy-file,non-alpha-in-dictionary,token-is-substring,unexpected-line-ending,whitespace-in-dictionary,minified-file,unsupported-configuration,no-files-to-check
        extra_dictionaries:
          cspell:software-terms/dict/softwareTerms.txt
          cspell:python/src/python/python-lib.txt
          cspell:python/src/python/python.txt
          cspell:npm/dict/npm.txt
          cspell:ruby/dict/ruby.txt
  comment-push:
    name: Report (Push)
    runs-on: ubuntu-latest
    needs: spelling
    permissions:
      contents: write
    if: (success() || failure()) && needs.spelling.outputs.followup && github.event_name == 'push'
    steps:
    - name: comment
      uses: check-spelling/check-spelling@main
      with:
        checkout: true
        task: ${{ needs.spelling.outputs.followup }}

  comment-pr:
    name: Report (PR)
    runs-on: ubuntu-latest
    needs: spelling
    permissions:
      contents: read
      pull-requests: write
    if: (success() || failure()) && needs.spelling.outputs.followup && contains(github.event_name, 'pull_request')
    steps:
    - name: comment
      uses: check-spelling/check-spelling@main
      with:
        checkout: true
        task: ${{ needs.spelling.outputs.followup }}
