name: Check Spelling

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  spelling:
    name: Check Spelling
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: codespell-project/actions-codespell@v2
      with:
        skip: docs/
        ignore_words_file: .whitelist